backend:
  name: github
  repo: arnadame/arnadame.github.io
  branch: main

media_folder: "public/static/images/uploads"
public_folder: "static/images/uploads"

collections:
  - name: "projects"
    label: "Projects"
    folder: "src/content/projects"
    create: true
    fields: 
      - { label: "File Name", name: "fileName", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Link", name: "link", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - { label: "Src", name: "src", widget: "image" }
          - { label: "Alt", name: "alt", widget: "string" }
  - name: "blogs"
    label: "Blogs"
    folder: "src/content/blogs"
    create: true
    fields: 
      - { label: "File Name", name: "fileName", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Paragraph", name: "paragraph", widget: "string" }
